### ISSUE TITLE
Tags and tests

### ISSUE THREAD

**Issue by jayvdb** [pakal/django-compat-patcher#1]
It would be helpful to be able to get the tests somehow, using a release.

GitHub doesnt have tags for v0.4.

The sdist release on PyPI doesnt include the tests.

Ideally the sdist does include the tests, usually using `MANIFEST.in`.  That is the easiest way for packagers to get the tests.

**Comment by pakal** [comment]
Thanks for the input, I've just added a release-0.4 tag, and modified the build so that tests will be included in the next 0.5 sdist (using graft in MANIFEST.in). 
This is currently in master branch.

**Comment by pakal** [comment]
release-0.5 includes unit-tests in the source distrib.
