### ISSUE TITLE
System checks

### ISSUE THREAD

**Issue by jayvdb** [pakal/django-compat-patcher#10]
This probably needs no new code, because the checks can be disabled using `SILENCED_SYSTEM_CHECKS`, however worth noting that these now cause a failure due to the check.  But I was able to delete old migrations and create new ones, and migrate

```
dbsnapshot.Server.host: (fields.E900) IPAddressField has been removed except for support in historical migrations.
	HINT: Use GenericIPAddressField instead.
dbsnapshot.Server.updated: (fields.E160) The options auto_now, auto_now_add, and default are mutually exclusive. Only one of these options may be present.
```

Maybe worthy of a note in the README that users should employ `SILENCED_SYSTEM_CHECKS` for these situations.

**Comment by pakal** [comment]
Thanks, add to Readme in commit 5821d02
