### ISSUE TITLE
templatetags static and translate/blocktranslate renamed in 3.1

### ISSUE THREAD

**Issue by jayvdb** [pakal/django-compat-patcher#13]
templatetag staticfiles was removed in 3.0, now 'static' must be used.  It was deprecated ages ago.

Lots of breakages as a result https://github.com/search?q=django+templatetags+staticfiles&type=Issues

Looking forward, https://docs.djangoproject.com/en/dev/topics/i18n/translation/#std:templatetag-blocktranslate was renamed in 3.1, thankfully old names not removed yet.

https://pypi.org/project/django-translation-aliases/ may be usable for forwards compatibility.

**Comment by pakal** [comment]
Django 3.1 has removed lots of utilities, a new set of fixers is needed indeed

**Comment by jayvdb** [comment]
I have a WIP for `static` (and a few others), but have been holding back due to lack of tests (and time).

**Comment by pakal** [comment]
Good, I've just added you to AUTHORS and released v0.8 of DCP ; I'll do a pass for more fixers but not until a few months from now

**Comment by pakal** [comment]
I'll check this staticfiles removal in the upcoming weeks

**Comment by pakal** [comment]
Ok staticfiles has its compatibility fixer in master; for blocktranslate, I'll wait for their removal to provide fixers (DCP has few foorward-compatibility-fixers, https://pypi.org/project/django-translation-aliases/ will do the job for those who want it ^^)
