### ISSUE TITLE
Command syncdb deprecated in 1.7

### ISSUE THREAD

**Issue by jayvdb** [pakal/django-compat-patcher#14]
```py
  File "/usr/lib/python3.8/site-packages/dmigrations/management/commands/syncdb.py", line 2, in <module>
    from django.core.management.commands.syncdb import Command as Original
ModuleNotFoundError: No module named 'django.core.management.commands.syncdb'
```

Replaced with `makemigrations` and `migrate` .  Maybe add an dummy command which emits a helpful error message.

**Comment by pakal** [comment]
I think the syncdb->migrate transition was loud enough for everyone in Django community to know about it   ^^

(PR accepted though)

**Comment by pakal** [comment]
Django1.7 is getting really old, the focus is now on fixers for Django >= 2.0, to help the ecosystem transition between the 5 latest versions
