### ISSUE TITLE
Django 4 is out

### ISSUE THREAD

**Issue by jayvdb** [pakal/django-compat-patcher#19]
Lots of deprecations wrt moved functions in Django 3 are now removed and no longer work.
e.g. `django.conf.urls.url` is now gone

**Comment by pakal** [comment]
Indeed, i'll have to make an update pass on DCP, although I don't know yet when I'll have time for that  ^^

**Comment by jayvdb** [comment]
> e.g. django.conf.urls.url is now gone

Another big problem I have encountered is `Signal` 's `provided_args` no longer being needed.
The next largest problem I have encountered so far is Middleware now needing `get_response`.

Those three account for nearly all problems I have encountered multiple times.

**Comment by pakal** [comment]
Thanks for the input, i'm slowly getting back on delayed stuffs so I expect to update my apps + DCP to Django 4 towards April ^^

**Comment by pakal** [comment]
I've begun adding fixers or Django 4, I've already added most "easy picks" to master branch, now I wonder how to handle NullBooleanField and postgres.JSONField disappearance

**Comment by pakal** [comment]
The "Middleware now needing get_response." will be some work too, but easier

**Comment by pakal** [comment]
New version of DCP is out with lots of fixers for Django4.0 : https://pypi.org/project/django-compat-patcher/0.11/

Hope it covers most of the needs of your older applications  B-)
