### ISSUE TITLE
test_django1_9_fixers.py::test_fix_deletion_contrib_sites_models_get_current_site fails

### ISSUE THREAD

**Issue by jayvdb** [pakal/django-compat-patcher#3]
I've got CI going at https://travis-ci.org/jayvdb/django-compat-patcher/builds/529502995 .  A lot of red, but mostly caused by the one test failing with `OperationalError: no such table: django_site`

**Comment by jayvdb** [comment]
CI is green if this fixer is removed. https://travis-ci.org/jayvdb/django-compat-patcher/builds/529519318

**Comment by pakal** [comment]
Ok fixed in latest release 0.6
